/**
 * Zeq OS Mathematical Framework - Quantum Mechanics Operators
 * Operators for quantum physics and quantum information theory
 */

import { ZeqOperator } from '../types';

export const QuantumMechanicsOperators: ZeqOperator[] = [
  {
    id: 'QM1',
    name: 'Wave Function Collapse',
    symbol: 'Ψ_C',
    domain: 'QuantumMechanics',
    formula: 'Ψ_C(|ψ⟩) = |n⟩⟨n|ψ⟩ / ||⟨n|ψ⟩||',
    description: 'Models quantum measurement and wave function collapse',
    associatedOperators: ['QM2', 'QM3'],
  },
  {
    id: 'QM2',
    name: 'Superposition Operator',
    symbol: 'Σ_Q',
    domain: 'QuantumMechanics',
    formula: 'Σ_Q(|ψ⟩) = Σᵢ cᵢ|φᵢ⟩ where Σ|cᵢ|² = 1',
    description: 'Creates quantum superposition states',
    associatedOperators: ['QM1', 'QM4'],
  },
  {
    id: 'QM3',
    name: 'Entanglement Generator',
    symbol: 'Ε_G',
    domain: 'QuantumMechanics',
    formula: 'Ε_G(|ψ⟩,|φ⟩) = (|00⟩ + |11⟩)/√2',
    description: 'Generates entangled quantum states',
    associatedOperators: ['QM1', 'QM5'],
  },
  {
    id: 'QM4',
    name: 'Quantum Interference',
    symbol: 'Ι_Q',
    domain: 'QuantumMechanics',
    formula: 'Ι_Q(ψ₁,ψ₂) = |ψ₁ + ψ₂|² = |ψ₁|² + |ψ₂|² + 2Re(ψ₁*ψ₂)',
    description: 'Models quantum interference patterns',
    associatedOperators: ['QM2', 'QM6'],
  },
  {
    id: 'QM5',
    name: 'Decoherence Operator',
    symbol: 'Δ_Q',
    domain: 'QuantumMechanics',
    formula: 'Δ_Q(ρ) = Σₖ EₖρEₖ† where Σ EₖEₖ† = I',
    description: 'Models quantum decoherence and environmental interaction',
    associatedOperators: ['QM3', 'QM7'],
  },
  {
    id: 'QM6',
    name: 'Quantum Tunneling',
    symbol: 'Τ_Q',
    domain: 'QuantumMechanics',
    formula: 'Τ_Q(E,V,a) = e^(-2κa) where κ = √(2m(V-E))/ℏ',
    description: 'Calculates tunneling probability through potential barriers',
    associatedOperators: ['QM4', 'QM8'],
  },
  {
    id: 'QM7',
    name: 'Heisenberg Uncertainty',
    symbol: 'Η_U',
    domain: 'QuantumMechanics',
    formula: 'Η_U(x,p) = σₓσₚ ≥ ℏ/2',
    description: 'Enforces uncertainty principle constraints',
    associatedOperators: ['QM5', 'QM9'],
  },
  {
    id: 'QM8',
    name: 'Quantum Spin',
    symbol: 'Σ_S',
    domain: 'QuantumMechanics',
    formula: 'Σ_S(s) = ℏ√(s(s+1)), Sᵢ|s,m⟩ = ℏmᵢ|s,m⟩',
    description: 'Computes spin angular momentum properties',
    associatedOperators: ['QM6', 'QM10'],
  },
  {
    id: 'QM9',
    name: 'Quantum Hamiltonian',
    symbol: 'Η_Q',
    domain: 'QuantumMechanics',
    formula: 'Η_Q = -ℏ²/2m ∇² + V(r)',
    description: 'Total energy operator for quantum systems',
    associatedOperators: ['QM7', 'QM11'],
  },
  {
    id: 'QM10',
    name: 'Density Matrix',
    symbol: 'Ρ_D',
    domain: 'QuantumMechanics',
    formula: 'Ρ_D = Σᵢ pᵢ|ψᵢ⟩⟨ψᵢ|',
    description: 'Represents mixed quantum states',
    associatedOperators: ['QM8', 'QM12'],
  },
  {
    id: 'QM11',
    name: 'Schrödinger Evolution',
    symbol: 'Υ_S',
    domain: 'QuantumMechanics',
    formula: 'Υ_S(|ψ(t)⟩) = e^(-iHt/ℏ)|ψ(0)⟩',
    description: 'Time evolution of quantum states',
    associatedOperators: ['QM9', 'QM13'],
  },
  {
    id: 'QM12',
    name: 'Von Neumann Entropy',
    symbol: 'Σ_V',
    domain: 'QuantumMechanics',
    formula: 'Σ_V(ρ) = -Tr(ρ log ρ)',
    description: 'Quantum entropy for density matrices',
    associatedOperators: ['QM10', 'QM14'],
  },
  {
    id: 'QM13',
    name: 'Quantum Gate',
    symbol: 'Γ_Q',
    domain: 'QuantumMechanics',
    formula: 'Γ_Q(U,|ψ⟩) = U|ψ⟩ where U†U = I',
    description: 'Unitary quantum gate operations',
    associatedOperators: ['QM11', 'QM15'],
  },
  {
    id: 'QM14',
    name: 'Fidelity Measure',
    symbol: 'Φ_F',
    domain: 'QuantumMechanics',
    formula: 'Φ_F(ρ,σ) = (Tr√(√ρ σ √ρ))²',
    description: 'Measures similarity between quantum states',
    associatedOperators: ['QM12', 'QM16'],
  },
  {
    id: 'QM15',
    name: 'Quantum Fourier Transform',
    symbol: 'Φ_QFT',
    domain: 'QuantumMechanics',
    formula: 'Φ_QFT|j⟩ = 1/√N Σₖ e^(2πijk/N)|k⟩',
    description: 'Quantum version of discrete Fourier transform',
    associatedOperators: ['QM13', 'QM17'],
  },
  {
    id: 'QM16',
    name: 'Bell State Generator',
    symbol: 'Β_S',
    domain: 'QuantumMechanics',
    formula: 'Β_S = {|Φ±⟩ = (|00⟩±|11⟩)/√2, |Ψ±⟩ = (|01⟩±|10⟩)/√2}',
    description: 'Generates maximally entangled Bell states',
    associatedOperators: ['QM14', 'QM18'],
  },
  {
    id: 'QM17',
    name: 'Pauli Operators',
    symbol: 'Π_P',
    domain: 'QuantumMechanics',
    formula: 'Π_P = {σₓ, σᵧ, σᵤ} with σᵢσⱼ = δᵢⱼI + iεᵢⱼₖσₖ',
    description: 'Fundamental single-qubit operations',
    associatedOperators: ['QM15', 'QM19'],
  },
  {
    id: 'QM18',
    name: 'CNOT Gate',
    symbol: 'Χ_CN',
    domain: 'QuantumMechanics',
    formula: 'Χ_CN|a,b⟩ = |a, a⊕b⟩',
    description: 'Controlled-NOT two-qubit gate',
    associatedOperators: ['QM16', 'QM20'],
  },
  {
    id: 'QM19',
    name: 'Hadamard Transform',
    symbol: 'Η_H',
    domain: 'QuantumMechanics',
    formula: 'Η_H = 1/√2 [1 1; 1 -1]',
    description: 'Creates superposition from computational basis',
    associatedOperators: ['QM17', 'QM1'],
  },
  {
    id: 'QM20',
    name: 'Phase Gate',
    symbol: 'Π_Φ',
    domain: 'QuantumMechanics',
    formula: 'Π_Φ(θ) = [1 0; 0 e^(iθ)]',
    description: 'Introduces relative phase in quantum state',
    associatedOperators: ['QM18', 'QM2'],
  },
];

export const getQuantumMechanicsOperator = (id: string): ZeqOperator | undefined => {
  return QuantumMechanicsOperators.find(op => op.id === id);
};
