
import { CommunityApp } from './types';

export interface ExtendedApp extends CommunityApp {
  layoutSize: 'large' | 'medium' | 'small';
}

export const COMMUNITY_APPS: ExtendedApp[] = [
  {
    id: '1',
    name: 'Mathematical Intelligence (MI)',
    developer: 'Core Team',
    description: 'The first AI that reasons through physics, not probability. Ask any question—MI routes it through 1549 kinematic operators and returns precision-verified answers synchronized to universal constants.',
    longDescription: 'Mathematical Intelligence represents a fundamental shift in how AI processes information. Instead of predicting the next token, MI maps your question to the appropriate physics domain, selects the optimal kinematic operators, and computes the answer through verified mathematical pathways. Every response is synchronized to the 1.287 Hz HulyaPulse and validated to ≤0.1% precision.',
    category: 'Utilities',
    rating: 5.0,
    downloads: 'BETA',
    imageUrl: '/IMG_4238.PNG',
    tags: ['AI', 'Physics', 'Precision'],
    isNew: true,
    price: 'Free',
    layoutSize: 'large'
  },
  {
    id: '2',
    name: 'AI Physics Upgrade for Chrome',
    developer: 'Engineering Team',
    description: 'Upgrade ChatGPT, Claude, and Gemini with physics-verified reasoning. This extension intercepts queries, applies operator validation, and returns precision-checked responses.',
    longDescription: 'Transform any AI chatbot into a physics-aware reasoning engine. The Chrome Extension intercepts physics, engineering, and mathematical queries before they reach the AI, enriches them with appropriate kinematic operators, and validates the responses against known physical constants. Turn probabilistic guesses into verified calculations.',
    category: 'Productivity',
    rating: 5,
    downloads: 'BETA',
    imageUrl: '/IMG_4239.PNG',
    tags: ['Chrome', 'AI', 'Validation'],
    isNew: true,
    price: 'Free',
    layoutSize: 'medium'
  },
  {
    id: '3',
    name: 'Developer SDK for VS Code',
    developer: 'SDK Team',
    description: 'Build physics-aware applications with full IntelliSense, real-time operator debugging, and one-click App Store publishing.',
    longDescription: 'The complete development environment for building synchronized physics applications. Get autocomplete for 1549 operators, visualize HulyaPulse synchronization in real-time, validate precision during development, and publish directly to the App Store. Includes templates for common physics domains.',
    category: 'Creative',
    rating: 5,
    downloads: 'BETA',
    imageUrl: '/IMG_4240.PNG',
    tags: ['SDK', 'VS Code', 'Development'],
    isNew: true,
    price: 'Free',
    layoutSize: 'small'
  },
  {
    id: '4',
    name: 'Community Hub',
    developer: 'Community',
    description: 'Connect with researchers, engineers, and developers building the future of computational physics. Share operators, verify results, and collaborate on solutions.',
    longDescription: 'The central meeting point for everyone working with synchronized physics. Whether you\'re a student learning the 7-Step methodology, a researcher proposing new operators, or an engineer solving real-world problems—this is where knowledge is shared, verified, and evolved.\n\nEvery solution posted is automatically validated against the ≤0.1% precision standard. Propose new operators for unexplored phenomena and watch them undergo rigorous community testing before joining the official spectrum.',
    category: 'Social',
    rating: 5,
    downloads: 'BETA',
    imageUrl: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&q=80&w=800',
    tags: ['Community', 'Collaboration', 'Research'],
    price: 'Free',
    layoutSize: 'medium'
  },
  {
    id: '5',
    name: 'Research Papers & Proofs',
    developer: 'Research Division',
    description: 'Access peer-reviewed papers defining the mathematical foundation: HulyaPulse discovery, Zeqond constant, KO42 synchronization, and the complete operator spectrum.',
    longDescription: 'The scientific foundation of synchronized physics. This repository contains the core papers that establish the mathematical framework: from the derivation of the 1.287 Hz HulyaPulse frequency to the complete formalization of 1549 kinematic operators across 34 physics domains. All papers are peer-deposited on Zenodo.',
    category: 'Creative',
    rating: 5,
    downloads: 'BETA',
    imageUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=800',
    tags: ['Research', 'Papers', 'Mathematics'],
    price: 'Free',
    layoutSize: 'medium'
  },
  {
    id: '6',
    name: 'Quantum Logic Solver',
    developer: 'Quantum Lab',
    description: 'Execute quantum logic operators with high-fidelity information entropy calculations. Shannon entropy, quantum scaling, and uncertainty quantification.',
    longDescription: 'A specialized tool for quantum information theory. Execute QL1 operators for Shannon entropy, quantum-logic scaling, and information-theoretic calculations—all synchronized to the HulyaPulse clock for maximum precision.',
    category: 'Utilities',
    rating: 5,
    downloads: 'v4.0',
    imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=800',
    tags: ['Quantum', 'Entropy', 'Information'],
    price: 'Free',
    layoutSize: 'small'
  },
  {
    id: '7',
    name: '3D Physics Simulator',
    developer: 'Core Team',
    description: 'Interactive visualization of synchronized physics: orbital mechanics, quantum waves, N-body gravity, and spacetime fabric—all at 1.287 Hz.',
    longDescription: 'See the framework in action. This multi-demo simulator visualizes orbital mechanics, quantum wave functions, N-body gravitational systems, particle fields, and spacetime curvature—all synchronized to the 1.287 Hz HulyaPulse. Built with React Three Fiber and the KO42 operator family.',
    category: 'Creative',
    rating: 5,
    downloads: 'BETA',
    imageUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&q=80&w=800',
    tags: ['3D', 'Visualization', 'Simulation'],
    isNew: true,
    price: 'Free',
    layoutSize: 'small',
    route: '/simulator'
  },
  {
    id: '8',
    name: 'Game Engine Sync',
    developer: 'SDK Team',
    description: 'Add 1.287 Hz synchronization to Unity, Unreal, Godot, Three.js, and more. One import, all engines locked to the Zeqond timebase.',
    longDescription: 'Drop-in synchronization for any game or physics engine. Import the plugin and your entire simulation locks to the 1.287 Hz HulyaPulse. Supports Unity, Unreal Engine, Godot, Three.js, Matter.js, Cannon.js, p5.js, D3.js, and Plotly.js. Build distributed systems that stay perfectly in sync.',
    category: 'Developer',
    rating: 5,
    downloads: 'BETA',
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=800',
    tags: ['Plugin', 'Unity', 'Three.js', 'Unreal'],
    isNew: true,
    price: 'Free',
    layoutSize: 'small',
    route: '/plugins'
  },
  {
    id: '9',
    name: '7-Step Verification Wizard',
    developer: 'Core Team',
    description: 'The interactive debugger for physics problems. Define, select operators, tensor, compile, execute, verify, and output—all guided step by step.',
    longDescription: 'The programming interface for synchronized physics. The wizard walks you through the complete 7-Step methodology: problem definition, domain selection, operator tensioning (KO42.1/KO42.2), master compilation, execution, precision verification, and unified output. Run in interactive or autotune mode to lock results within ≤0.1% mean error.',
    category: 'Developer',
    rating: 5,
    downloads: 'BETA',
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800',
    tags: ['Verification', '7-Step', 'Debugging'],
    isNew: true,
    price: 'Free',
    layoutSize: 'medium',
    route: '/wizard'
  },
  {
    id: '10',
    name: 'HITE Encryption v2.0',
    developer: 'Security Team',
    description: 'Physics-backed encryption: AES-256-GCM with temporal entanglement. Every file includes a Landauer Certificate proving brute-force is thermodynamically impossible.',
    longDescription: 'HITE (HULYAS Information-Theoretic Encryption) combines AES-256-GCM with temporal synchronization to the 1.287 Hz pulse. Unlike traditional encryption that relies only on computational hardness, HITE provides physical proof that brute-force attacks require more energy than exists in trillions of suns.\n\nKey Features:\n• AES-256-GCM authenticated encryption\n• KO42 Time-Lock with synchronized entropy\n• Landauer Certificate proving attack impossibility\n• Attack Energy Required: 3.34×10⁵⁶ J (trillions of sun-lifetimes)',
    category: 'Utilities',
    rating: 5,
    downloads: 'BETA',
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=800',
    tags: ['Security', 'Encryption', 'AES-256'],
    isNew: true,
    price: 'Free',
    layoutSize: 'small'
  },
  {
    id: '11',
    name: 'AI Skill Studio',
    developer: 'Core Team',
    description: 'Create custom AI skills for any industry with HulyaPulse synchronization. Generate, install, and share skills for Claude, GPT-4, Llama, and more.',
    longDescription: 'The AI Skill Studio lets you create and install mathematically intelligent skills into any LLM. Each skill includes operator definitions, precision targets, and the 7-step protocol for verified calculations.\n\nFeatures:\n• 12 industry templates (Healthcare, Aerospace, Finance, etc.)\n• Custom skill generator with API integration\n• Pre-built skills: ZEQ OS MI Kernel, HF Forensic Intelligence\n\nAll skills operate at 1.287 Hz HulyaPulse frequency.',
    category: 'Utilities',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=800',
    tags: ['Skills', 'AI', 'LLM', 'Studio'],
    isNew: true,
    price: 'Free',
    layoutSize: 'medium',
    route: '/skills'
  },
  {
    id: '12',
    name: 'Orbital Mission Planner',
    developer: 'Aerospace Lab',
    description: 'Plan orbital transfers with Hohmann maneuvers, delta-v budgets, and 3D orbit visualization. All calculations synchronized to HulyaPulse.',
    longDescription: 'A comprehensive orbital mechanics toolkit for planning satellite transfers and space missions. Compute Hohmann transfer orbits, calculate delta-v budgets, visualize departure and arrival orbits with interactive SVG diagrams, and verify all calculations against known reference values with ≤0.1% precision.\n\nOperators: HOHMANN_TRANSFER, ORBIT_VELOCITY, ORBIT_PERIOD, ORBIT_ESCAPE',
    category: 'Utilities',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&q=80&w=800',
    tags: ['Aerospace', 'Orbital', 'Delta-V', 'Hohmann'],
    isNew: true,
    price: 'Free',
    layoutSize: 'medium',
    route: '/orbital-planner'
  },
  {
    id: '13',
    name: 'Financial Risk Analyzer',
    developer: 'Finance Team',
    description: 'Monte Carlo VaR simulation, Black-Scholes pricing, and portfolio risk metrics with precision-verified calculations.',
    longDescription: 'Analyze financial risk with physics-grade precision. Run Monte Carlo simulations to estimate Value at Risk, price options with Black-Scholes, and compute Sharpe ratios, CVaR, and max drawdown estimates—all with Shannon entropy verification and HulyaPulse synchronization.\n\nOperators: VAR_MONTE_CARLO, BLACK_SCHOLES, BOND_YIELD',
    category: 'Productivity',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&q=80&w=800',
    tags: ['Finance', 'Risk', 'Monte Carlo', 'VaR'],
    isNew: true,
    price: 'Free',
    layoutSize: 'medium',
    route: '/financial-analyzer'
  },
  {
    id: '14',
    name: 'Medical Dosage Calculator',
    developer: 'Medical Lab',
    description: 'GFR, BMI, BSA, and weight-based dosage calculations with safety checks and renal function assessment.',
    longDescription: 'Clinical calculation toolkit with multi-tab interface for GFR (Cockcroft-Gault), BMI, BSA (DuBois formula), and weight-adjusted dosing. Includes automatic safety warnings for renal impairment, obesity-related dosing adjustments, and precision verification against reference values.\n\nOperators: MED_GFR, MED_BMI, MED_BSA, MED_DOSE',
    category: 'Utilities',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800',
    tags: ['Medical', 'Dosage', 'GFR', 'Clinical'],
    isNew: true,
    price: 'Free',
    layoutSize: 'medium',
    route: '/medical-calculator'
  },
  {
    id: '15',
    name: 'Structural Engineering Toolkit',
    developer: 'Engineering Div',
    description: 'Beam deflection analysis, stress calculations, and SVG beam diagrams for structural engineering applications.',
    longDescription: 'Interactive structural analysis with SVG beam visualization showing loads, reactions, and deflection curves. Supports simply-supported beams with uniform and point loads, automatic moment of inertia calculation for rectangular sections, and multi-material presets (Steel, Aluminum, Wood).\n\nFeatures: Beam diagrams, deflection curves, bending stress, shear stress, safety factor analysis.',
    category: 'Utilities',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=80&w=800',
    tags: ['Engineering', 'Structural', 'Beam', 'Stress'],
    isNew: true,
    price: 'Free',
    layoutSize: 'small',
    route: '/engineering-toolkit'
  },
  {
    id: '16',
    name: 'Neural Signal Processor',
    developer: 'Neuro Lab',
    description: 'Simulated EEG waveform generation, spectral power analysis, and signal entropy measurement for neuroscience.',
    longDescription: 'Process neural signals with real-time waveform visualization on canvas, spectral analysis across frequency bands (delta, theta, alpha, beta, gamma), and Shannon entropy computation for signal complexity. HulyaPulse modulates alpha wave amplitude for synchronized analysis.\n\nFeatures: EEG waveform display, DFT power spectrum, frequency band analysis, signal entropy.',
    category: 'Creative',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?auto=format&fit=crop&q=80&w=800',
    tags: ['Neuroscience', 'EEG', 'Signal', 'Spectral'],
    isNew: true,
    price: 'Free',
    layoutSize: 'small',
    route: '/neural-processor'
  },
  {
    id: '17',
    name: 'Climate & Environment Modeler',
    developer: 'Climate Team',
    description: 'Temperature projections, CO2 modeling, radiative forcing, and renewable energy metrics for climate science.',
    longDescription: 'Model climate change scenarios with multi-pathway temperature projections (RCP 2.6, 4.5, 8.5), CO2 concentration forecasting, radiative forcing calculations, and energy source comparisons. Includes solar/wind capacity factors and carbon intensity metrics.\n\nFeatures: Scenario projection charts, emissions calculator, energy EROI comparison.',
    category: 'Utilities',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1569163139394-de4e4f43e4e3?auto=format&fit=crop&q=80&w=800',
    tags: ['Climate', 'Environment', 'CO2', 'Energy'],
    isNew: true,
    price: 'Free',
    layoutSize: 'medium',
    route: '/climate-modeler'
  },
  {
    id: '18',
    name: 'Robotics Kinematics Lab',
    developer: 'Robotics Team',
    description: '2D robot arm visualization with forward and inverse kinematics solver for 3-link planar manipulators.',
    longDescription: 'Interactive robotics kinematics laboratory with SVG 2D visualization of a 3-link planar robot arm. Adjust joint angles with sliders for forward kinematics, or specify target positions for inverse kinematics using geometric solutions. Includes workspace boundary visualization and real-time end-effector tracking.\n\nFeatures: FK/IK solver, joint angle control, workspace visualization.',
    category: 'Creative',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80&w=800',
    tags: ['Robotics', 'Kinematics', 'FK/IK', 'Manipulator'],
    isNew: true,
    price: 'Free',
    layoutSize: 'small',
    route: '/robotics-lab'
  },
  {
    id: '19',
    name: 'Quantum Circuit Designer',
    developer: 'Quantum Lab',
    description: 'Visual quantum circuit builder with gate placement, fidelity estimation, and circuit depth analysis.',
    longDescription: 'Design quantum circuits with an interactive SVG-based builder supporting H, X, Y, Z, T, S, CNOT, SWAP, and CZ gates. Place gates on qubit lines, visualize circuit structure, and compute fidelity estimates based on gate error rates. Tracks circuit depth, T-count, and total gate count.\n\nFeatures: Drag-and-place circuit builder, gate palette, fidelity metrics.',
    category: 'Creative',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&q=80&w=800',
    tags: ['Quantum', 'Circuit', 'Qubits', 'Gates'],
    isNew: true,
    price: 'Free',
    layoutSize: 'small',
    route: '/quantum-circuits'
  },
  {
    id: '20',
    name: 'Materials Science Explorer',
    developer: 'Materials Lab',
    description: 'Stress-strain curves, fatigue life estimation, and material property comparison for engineering materials.',
    longDescription: 'Explore material properties with interactive stress-strain curve visualization, S-N fatigue life calculation, and side-by-side material comparison. Includes preset data for Steel 1018, Aluminum 6061, Titanium Ti-6Al-4V, and Carbon Fiber composite.\n\nFeatures: Stress-strain plots, yield/UTS markers, Goodman fatigue analysis, material database.',
    category: 'Utilities',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1615818499660-30bb5816e1c7?auto=format&fit=crop&q=80&w=800',
    tags: ['Materials', 'Stress', 'Fatigue', 'Engineering'],
    isNew: true,
    price: 'Free',
    layoutSize: 'small',
    route: '/materials-explorer'
  },
  {
    id: '21',
    name: 'Cosmic Background Analyzer',
    developer: 'Astro Team',
    description: 'CMB temperature map visualization, angular power spectrum analysis, and cosmological parameter display.',
    longDescription: 'Analyze the Cosmic Microwave Background with a 2D temperature fluctuation heatmap, angular power spectrum showing acoustic peaks, and precision-verified cosmological parameters from Planck 2018 data. Includes Hubble constant, dark energy/matter fractions, and universe age calculations.\n\nFeatures: CMB heatmap, power spectrum chart, Planck parameter verification.',
    category: 'Creative',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&q=80&w=800',
    tags: ['Cosmic', 'CMB', 'Cosmology', 'Planck'],
    isNew: true,
    price: 'Free',
    layoutSize: 'medium',
    route: '/cosmic-analyzer'
  },
  {
    id: '22',
    name: 'Vehicle Dynamics Analyzer',
    developer: 'Transport Lab',
    description: 'Bicycle model cornering, quarter-car suspension ODE, Pacejka tire model, and braking load transfer analysis.',
    longDescription: 'Comprehensive vehicle dynamics toolkit with bicycle model cornering analysis, RK4 quarter-car suspension simulation, Pacejka Magic Formula tire force computation, and braking load transfer calculations. Includes SVG top-down vehicle visualization with force vectors and Canvas suspension response charts.\n\nAlgorithms: Bicycle model, RK4 ODE solver, Pacejka Magic Formula (B=10, C=1.9, D=1.0, E=0.97)',
    category: 'Utilities',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&q=80&w=800',
    tags: ['Vehicle', 'Dynamics', 'Suspension', 'Tire'],
    isNew: true,
    price: 'Free',
    layoutSize: 'medium',
    route: '/vehicle-dynamics'
  },
  {
    id: '23',
    name: 'Aerodynamics Wind Tunnel',
    developer: 'Aero Team',
    description: 'NACA 4-digit airfoil generator, panel method flow solver, streamline integration, and Cp pressure distribution.',
    longDescription: 'Virtual wind tunnel with NACA 4-digit airfoil generation, thin airfoil theory lift prediction, pressure coefficient distribution, and Blasius boundary layer thickness computation. Canvas flow field visualization with streamlines around the airfoil and pressure coloring.\n\nAlgorithms: NACA airfoil generator, thin airfoil Cl=2πα, Blasius boundary layer δ=5x/√Rex',
    category: 'Utilities',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1540962351504-03099e0a754b?auto=format&fit=crop&q=80&w=800',
    tags: ['Aerodynamics', 'Airfoil', 'NACA', 'Wind Tunnel'],
    isNew: true,
    price: 'Free',
    layoutSize: 'medium',
    route: '/aero-wind-tunnel'
  },
  {
    id: '24',
    name: 'Traffic Flow Optimizer',
    developer: 'Transport Lab',
    description: 'Dijkstra/A* pathfinding, LWR macroscopic traffic model, Godunov flux scheme, and Webster signal timing.',
    longDescription: 'Traffic flow analysis and optimization with interactive road network graph, congestion visualization, shortest-path routing, and signal timing optimization. Includes LWR macroscopic model with Godunov numerical scheme and space-time density heatmap.\n\nAlgorithms: Dijkstra, A*, LWR dρ/dt + d(ρv)/dx = 0, Webster C_opt = (1.5L+5)/(1-Σyi)',
    category: 'Utilities',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&q=80&w=800',
    tags: ['Traffic', 'Pathfinding', 'LWR', 'Signal Timing'],
    isNew: true,
    price: 'Free',
    layoutSize: 'small',
    route: '/traffic-optimizer'
  },
  {
    id: '25',
    name: 'Neural Architecture Designer',
    developer: 'ML Lab',
    description: 'Forward dimension tracking, exact parameter counts, FLOP estimation, and gradient flow analysis with vanishing/exploding detection.',
    longDescription: 'Design and analyze neural network architectures with layer-by-layer dimension tracking, parameter counting, and computational cost estimation. Supports Conv2D, Dense, LSTM, and Pooling layers. SVG architecture diagram with gradient magnitude flow analysis.\n\nAlgorithms: Conv2D/Dense/LSTM param counting, FLOP estimation, gradient magnitude flow detection',
    category: 'Creative',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800',
    tags: ['Neural Network', 'Architecture', 'Deep Learning', 'ML'],
    isNew: true,
    price: 'Free',
    layoutSize: 'medium',
    route: '/neural-architect'
  },
  {
    id: '26',
    name: 'Reinforcement Learning Playground',
    developer: 'ML Lab',
    description: 'Q-learning and SARSA on configurable grid world with epsilon-greedy exploration and convergence detection.',
    longDescription: 'Interactive reinforcement learning environment with configurable grid worlds, walls, and rewards. Train Q-learning or SARSA agents with epsilon-greedy exploration and watch policy convergence in real-time. SVG grid world with policy arrows and Q-table heatmap.\n\nAlgorithms: Q-learning, SARSA, epsilon-greedy, TD error tracking, convergence detection',
    category: 'Creative',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=800',
    tags: ['RL', 'Q-Learning', 'SARSA', 'Grid World'],
    isNew: true,
    price: 'Free',
    layoutSize: 'medium',
    route: '/rl-playground'
  },
  {
    id: '27',
    name: 'Signal Classification Studio',
    developer: 'ML Lab',
    description: 'FFT power bands, spectral centroid, KNN classifier, confusion matrix, and ROC curve with AUC computation.',
    longDescription: 'Classify signals using frequency-domain features and K-nearest neighbors. Generate sine, square, triangle, noise, and chirp signals, extract FFT features, and evaluate classification with confusion matrix, precision/recall/F1, and ROC curves.\n\nAlgorithms: Cooley-Tukey FFT, spectral centroid, ZCR, KNN (K=5), ROC/AUC',
    category: 'Creative',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800',
    tags: ['Signal', 'FFT', 'Classification', 'KNN'],
    isNew: true,
    price: 'Free',
    layoutSize: 'small',
    route: '/signal-classifier'
  },
  {
    id: '28',
    name: 'Fluid Dynamics Simulator',
    developer: 'Physics Lab',
    description: 'D2Q9 lattice Boltzmann method with BGK collision, vorticity computation, and drag coefficient analysis.',
    longDescription: 'Real-time fluid dynamics simulation using the D2Q9 Lattice Boltzmann Method. Visualize flow around obstacles with velocity magnitude heatmaps, velocity vectors, and vorticity colormaps with marching squares isolines. Compute Reynolds number and drag coefficient.\n\nAlgorithms: D2Q9 LBM, BGK collision, vorticity field, marching squares, Cd computation',
    category: 'Utilities',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&q=80&w=800',
    tags: ['Fluid', 'LBM', 'CFD', 'Vorticity'],
    isNew: true,
    price: 'Free',
    layoutSize: 'medium',
    route: '/fluid-dynamics'
  },
  {
    id: '29',
    name: 'Thermodynamic Cycle Analyzer',
    developer: 'Physics Lab',
    description: 'Carnot, Otto, Diesel, Rankine, and Brayton cycle analysis with P-V and T-S diagram visualization.',
    longDescription: 'Analyze five major thermodynamic cycles with full state-point calculations. Interactive P-V and T-S diagrams with animated working point tracing the cycle. Compute thermal efficiency, work output, and heat transfer for each process.\n\nAlgorithms: Isothermal, adiabatic, isobaric, isochoric processes, Carnot/Otto/Diesel/Rankine/Brayton',
    category: 'Utilities',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&q=80&w=800',
    tags: ['Thermodynamics', 'Carnot', 'Otto', 'Brayton'],
    isNew: true,
    price: 'Free',
    layoutSize: 'medium',
    route: '/thermo-cycles'
  },
  {
    id: '30',
    name: 'Electromagnetic Field Visualizer',
    developer: 'Physics Lab',
    description: 'Coulomb E-field superposition, Biot-Savart B-field, dipole antenna pattern, and EM wave propagation.',
    longDescription: 'Visualize electromagnetic fields with interactive charge placement, electric field lines, equipotential contours, and magnetic field computation. Includes half-wave dipole antenna radiation pattern and animated EM wave propagation with Poynting vector.\n\nAlgorithms: Coulomb superposition, Biot-Savart, half-wave dipole F(θ), EM wave animation',
    category: 'Utilities',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800',
    tags: ['EM', 'Electric Field', 'Antenna', 'Wave'],
    isNew: true,
    price: 'Free',
    layoutSize: 'medium',
    route: '/em-fields'
  },
  {
    id: '31',
    name: 'Pharmacokinetics Modeler',
    developer: 'BioTech Lab',
    description: '1- and 2-compartment PK models, IV/oral dosing, AUC, Cmax/Tmax, and multiple-dose accumulation.',
    longDescription: 'Model drug pharmacokinetics with 1-compartment and 2-compartment models using RK4 ODE integration. Simulate IV bolus and oral dosing with multiple-dose accumulation, therapeutic window visualization, and steady-state prediction.\n\nAlgorithms: 1/2-compartment PK, RK4 ODE, trapezoidal AUC, Cmax/Tmax, accumulation factor',
    category: 'Utilities',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&q=80&w=800',
    tags: ['Pharma', 'PK', 'Dosing', 'AUC'],
    isNew: true,
    price: 'Free',
    layoutSize: 'medium',
    route: '/pharma-kinetics'
  },
  {
    id: '32',
    name: 'Genomics Sequence Analyzer',
    developer: 'BioTech Lab',
    description: 'Needleman-Wunsch and Smith-Waterman alignment, neighbor-joining phylogeny, GC content, and Jukes-Cantor distance.',
    longDescription: 'Analyze DNA sequences with global (Needleman-Wunsch) and local (Smith-Waterman) alignment algorithms. Build phylogenetic trees using neighbor-joining method. Compute GC content, Jukes-Cantor evolutionary distance, and sequence identity.\n\nAlgorithms: NW global alignment, SW local alignment, neighbor-joining tree, Jukes-Cantor distance',
    category: 'Creative',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?auto=format&fit=crop&q=80&w=800',
    tags: ['Genomics', 'Alignment', 'Phylogeny', 'DNA'],
    isNew: true,
    price: 'Free',
    layoutSize: 'medium',
    route: '/genomics-analyzer'
  },
  {
    id: '33',
    name: 'Biomechanics Analyzer',
    developer: 'BioTech Lab',
    description: '2D inverse dynamics, Hill muscle model, gait cycle kinematics, and ground reaction force analysis.',
    longDescription: 'Analyze human biomechanics with 2D inverse dynamics for the lower extremity (thigh-shank-foot). Visualize gait cycle with animated stick-figure skeleton, ground reaction force vectors, and joint moment plots. Includes Hill muscle model for force-length and force-velocity relationships.\n\nAlgorithms: Newton-Euler inverse dynamics, Hill muscle model, sinusoidal gait kinematics',
    category: 'Creative',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=800',
    tags: ['Biomechanics', 'Gait', 'Inverse Dynamics', 'Muscle'],
    isNew: true,
    price: 'Free',
    layoutSize: 'small',
    route: '/biomechanics'
  },
  {
    id: '34',
    name: 'Seismology Station',
    developer: 'GeoScience Lab',
    description: 'P/S wave propagation through layered Earth, seismogram synthesis, magnitude estimation, and epicenter triangulation.',
    longDescription: 'Seismological analysis station with P/S wave ray tracing through Earth layers using Snell\'s law. Generate synthetic seismograms, estimate earthquake magnitude (Richter/moment), and triangulate epicenters from multiple station observations.\n\nAlgorithms: Snell\'s law refraction, damped sinusoid synthesis, Richter/Mw magnitude, circle triangulation',
    category: 'Utilities',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1509023464722-18d996393ca8?auto=format&fit=crop&q=80&w=800',
    tags: ['Seismology', 'Earthquake', 'Waves', 'Triangulation'],
    isNew: true,
    price: 'Free',
    layoutSize: 'medium',
    route: '/seismology'
  },
  {
    id: '35',
    name: 'Ocean Dynamics Lab',
    developer: 'GeoScience Lab',
    description: 'Airy wave theory, dispersion relation solver, tidal harmonics, Ekman spiral, and Stokes drift computation.',
    longDescription: 'Comprehensive ocean dynamics laboratory with Airy wave theory for surface gravity waves, tidal harmonic analysis (M2/S2/K1/O1), Ekman spiral current profiles, and Stokes drift computation. Animated wave cross-sections with orbital motion and 30-day tidal predictions.\n\nAlgorithms: Airy dispersion, tidal harmonics, Ekman spiral, Stokes drift, Pierson-Moskowitz spectrum',
    category: 'Utilities',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1505142468610-359e7d316be0?auto=format&fit=crop&q=80&w=800',
    tags: ['Ocean', 'Waves', 'Tides', 'Ekman'],
    isNew: true,
    price: 'Free',
    layoutSize: 'medium',
    route: '/ocean-dynamics'
  },
  {
    id: '36',
    name: 'Power Grid Analyzer',
    developer: 'GeoScience Lab',
    description: 'Newton-Raphson AC power flow, Y-bus matrix, Jacobian computation, 3-phase fault current, and voltage stability.',
    longDescription: 'Analyze electrical power systems with Newton-Raphson AC power flow solution. Build Y-bus admittance matrix, compute Jacobian, and solve for bus voltages iteratively. Includes 3-phase fault current analysis using Thevenin equivalent and single-line grid diagram with animated power flow.\n\nAlgorithms: Newton-Raphson power flow, Y-bus construction, Jacobian, Thevenin fault analysis',
    category: 'Utilities',
    rating: 5,
    downloads: 'NEW',
    imageUrl: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&q=80&w=800',
    tags: ['Power Grid', 'Power Flow', 'Fault Analysis', 'Voltage'],
    isNew: true,
    price: 'Free',
    layoutSize: 'medium',
    route: '/power-grid'
  }
];
